
services:
  redis-todo:
    image: redis:6.2
    container_name: redis-todo
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  users-api:
    build:
      context: ./users-api
    container_name: users-api
    ports:
      - "8083:8083"
    depends_on:
      - zipkin

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    depends_on:
      - users-api
      - zipkin

  todos-api:
    build:
      context: ./todos-api
    container_name: todos-api
    ports:
      - "8082:8082"
    depends_on: 
      - redis-todo
      - zipkin
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  
    depends_on:
      - auth-api
      - todos-api
      - zipkin

